name: build
on:
  push:
    branches:
      - "**"
    tags:
      - "v*"
  pull_request:

jobs:
  inverter_gui_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Setup"
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

      - name: Test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic  ./...

      - name: Upload code coverage
        uses: codecov/codecov-action@v1

      - name: Generate docker image labels and tags
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: ghcr.io/diebietse/invertergui
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
